      // Original Slope {name: "SLOPE", url: "https://slope-game-dusky.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmm7S2dquLUBl5Nq9nh-MCU19sAT3CbuqEmQ&s"},
    const games = [
      {name: "SLOPE", url: "https://slopeonline.vercel.app/file/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmm7S2dquLUBl5Nq9nh-MCU19sAT3CbuqEmQ&s"},
      {name: "1V1 LOL", url: "games/lol.html", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSEbIjGbQ7kWQzBt3gyygxzuDLgzGukjbyEg&s"},
      {name: "GRIM DONUT GAME (FIXED!)", url: "https://pinkbike.netlify.app/", image: "https://pro2-bar-s3-cdn-cf3.myportfolio.com/950086f2-7bd1-4fb7-b47a-8a644eedc078/e44e47e5-d279-4a55-b510-b4210ee074d1_rw_1920.jpg?h=81ba5a442bb63a30b11d49b6ac1b5089"},
      {name: "GROW A GARDEN (BROKEN!)", url: "https://maddox.page/basic-ruffle-player/html/grow_a_garden/index.html", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2WVA1dne-Kt3LbqoS_j6prkI4Gr9miUPefw&s"},
      {name: "TAP GOAL (NEW!)", url: "https://tapgoal.vercel.app", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEk0TcvUwygtRNJt13PyJbcLjhn0R66ZgaXA&s"},
      {name: "SLOWROADS", url: "https://slow-roads.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT76btQTGOYcbq_of2VE8gwxwY8xt3xaGy9Mw&s"},
      {name: "WEB MINECRAFT", url: "https://eagler.colbster937.dev/", image: "https://i.pinimg.com/originals/ca/a6/28/caa6283ceefc113183760312d522de53.jpg"},
      {name: "SUPERHOT", url: "https://semag.netlify.app/games/superhot/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5NRo3TfhUTGLYa6NPJv9341KXWqN-1RdAUQ&s"},
      {name: "ULTRAKILL (NEW!)", url: "pureplay-ultrakill.vercel.app", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjwhUz8bZZbtxkTPNvc976XkRaa8G_glQNlw&s"},
      {name: "INFINITE CRAFT", url: "https://www.infinitecraft.now/game/index.html", image: "https://play-lh.googleusercontent.com/YJFHGSmrMGuUqyWZ0oZDgDtDErIU2jQY3yT_PG9IRL6s5dBLmKXrXQShM3n8HFoPhkM=w240-h480-rw"},
      {name: "INFINITE CRAFT RECIPE BOOK", url: "https://infinite-craft-recipe.vercel.app/", image: "https://images.rawpixel.com/image_png_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTA5L2pvYjk2MC0xMzgtcC5wbmc.png"},
      {name: "HEX GL", url: "https://hexvelocity-hexgl-clone-racing-game.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOG6prUHS7lg-lqQfob2rkN1NON9ROLi-VMA&s"},
      {name: "GRANNY (BROKEN!)", url: "https://maddox.page/basic-ruffle-player/html/granny/index.html", image: "https://static.wikia.nocookie.net/4297c488-a874-4f33-91e7-ff16a1947afc/scale-to-width/755"},
      {name: "CRAZY CATTLE 3D", url: "https://maddox.page/basic-ruffle-player/html/crazycattle3d/index.html", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8oUe9IvLPfKQx449SgYDkCUu3g36HQk_bVqIrQoMMyoFNYTjs4EgLYSigUmHyB4vFkLo&usqp=CAU"},
      {name: "1.8 SERVER LIST MC", url: "https://eaglerhackedclients.vercel.app/servers.html", image: "https://static.vecteezy.com/system/resources/previews/000/380/983/non_2x/list-vector-icon.jpg"},
      {name: "POLYTRACK (FIXED!)", url: "https://polytrack-game.netlify.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbrhsc73QbzVS_fiL_QarswLDpKEEqpWKJyQ&s"},
      {name: "RIPOFF ROCKET LEAGUE", url: "https://semag.netlify.app/games/rocketsoccer/", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Rocket_League_coverart.jpg/250px-Rocket_League_coverart.jpg"},
      {name: "STEAL A BRAINROT", url: "https://maddox.page/basic-ruffle-player/html/steal_a_brainrot/index.html", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJKGxJt79VWj0CpMhv42h9xht0qIb8EymPlg&s"},
      {name: "PORTAL", url: "https://semag.netlify.app/games/portal/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH8JJnhsycO1P-u1ZKex6U2JpBdQ3ndih_aQ&s"},
      {name: "PORTAL 2", url: "https://semag.netlify.app/games/portal2/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUw3KKkkrkcHizRwGRR_WL72b7shd4PDg5xw&s"},
      {name: "SUPER MARIO 64", url: "https://supermario64.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiN69nLIKU4pTLGbgtREAoGgW2ko02Nf_-Vg&s"},
      {name: "SUPER MARIO BROS", url: "https://semag.netlify.app/games/supermariobros/", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/2560px-Mario_Series_Logo.svg.png"},
      {name: "OCARINA OF TIME", url: "https://semag.netlify.app/games/ocarinaoftime/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgfPkQJxURwfqNUu2Gl0T8OYwggRPsQc7iRA&s"},
      {name: "MAJORA'S MASK", url: "https://semag.netlify.app/games/majorasmask/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHniqgRkdQMJJ5-es6iIEudvlbHELDwmPxsA&s"},
      {name: "ELASTIC MAN", url: "https://elastic-man.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRunsT8Usbv6cAGP938_wjuk52dL_Tws2C_fg&s"},
      {name: "BLOXORS (NEW!)", url: "https://semag.netlify.app/games/bloxors/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLH0EmQGEXMsxUZtYqJN0WTaht7mOxTmtXdQ&s"},
      {name: "WORLD'S HARDEST GAME", url: "https://semag.netlify.app/games/worldshardestgame/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkaZndZxj7y4wJNTkesAT-tVyLtrs8L1ytnw&s"},
      {name: "FALL GUYS RIPOFF", url: "https://unblockedgamesworld.netlify.app/play/just-fall/", image: "https://logos-world.net/wp-content/uploads/2023/03/Fall-Guy-Logo.png"},
      {name: "CORE BALL", url: "https://unblockedgamesworld.netlify.app/play/core-ball/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYlfRJf7CdNh5HLooIul0TivTEjrAJdV8pZw&s"},
      {name: "CS SHOOTER", url: "https://maddox.page/basic-ruffle-player/html/cs_online/index.html", image: "https://logodix.com/logo/2115848.png"},
      {name: "TUNNEL RUSH", url: "https://semag.netlify.app/games/tunnelrush/", image: "https://i.pinimg.com/564x/38/f4/28/38f4284e72a11faa6db06d2d0e752210.jpg"},
      {name: "STICKMAN HOOK", url: "https://semag.netlify.app/games/stickmanhook/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJvVsEUpYC9LoysodejNXht7gE1uL0aF28Sg&s"},
      {name: "MOTO X3M", url: "https://moto-x3m-chi.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDAa2cL87GKVZQDjg7xZhXITfqvvqTOKkeHg&s"},
      {name: "MOTO X3M 2", url: "https://unblockedgamesworld.netlify.app/play/motox3m2/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzeU9vvvk3avQ2fjLAyTHb3MI2YaLjvY7cOA&s"},
      {name: "MOTO X3M WINTER", url: "https://semag.netlify.app/games/motox3mwinter/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5EShHpEgwGph31rkwQXgwptQ0qFAJUh4yFw&s"},
      {name: "DELTARUNE", url: "https://maddox.page/basic-ruffle-player/html/deltarune/index.html", image: "https://mediaproxy.tvtropes.org/width/1200/https://static.tvtropes.org/pmwiki/pub/images/deltarune.jpeg"},
      {name: "BALDI'S BASICS", url: "https://semag.netlify.app/games/baldisbasics/", image: "https://fontmeme.com/images/badis-basics-font.png"},
      {name: "RETRO BOWL", url: "https://semag.netlify.app/games/retrobowl/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNjsvRZFAy3jkJhepJkM5dIgpW2G2hFiAYLg&s"},
      {name: "RETRO BOWL COLLAGE", url: "https://r-js-games-v2.vercel.app/retrobowl-coll/", image: "https://upload.wikimedia.org/wikipedia/en/b/bf/Retro_Bowl_cover.png"},
      {name: "BASKETBALL RANDOM", url: "https://basket-random-omega.vercel.app/", image: "https://play-lh.googleusercontent.com/gP8T5Z1O-ngxIloiwcBZzrzyLPYDp0R_1BDNKUDZboIRPVImeyWI8-7aExvB9gAGNKc"},
      {name: "8 BALL POOL", url: "https://playpool.vercel.app/", image: "https://upload.wikimedia.org/wikipedia/en/0/0c/8_Ball_Pool_cover.jpg"},
      {name: "PAPA'S PIZZARIA", url: "https://semag.netlify.app/games/papaspizzaria/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIXLo6S0IWyYu4JERrO1fbMLcVMxOYL678Tw&s"},
      {name: "SHREK 2", url: "https://semag.netlify.app/games/shrek2/", image: "https://ih1.redbubble.net/image.1926840049.0477/bg,f8f8f8-flat,750x,075,f-pad,750x1000,f8f8f8.jpg"},
      {name: "SANDBOXELS", url: "https://shalbito.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP4mGq3818HuYixoDz7ZehmbqMQZnO1gWe-w&s"},
      {name: "ALIEN HOMONID", url: "https://glitched-studios-student-help-website.vercel.app/pages/math/alienhominid/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz8cuo_xM0jIElMGGjU2GLuQNDvZ8-r7-3IQ&s"},
      {name: "MINI ARCADE DRIVING", url: "https://3d-driving-ai.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIrOUEZFkwbAPw-IPiZS3I2ccESOPvnBj5zg&s"},
      {name: "BLUE CIRCLE", url: "https://games.theinfoport.com/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRz7LsxjtzTvkGiLZxMqH-ot0n4yHScIt0YLQ&s"},
      {name: "RAFT WARS", url: "https://semag.netlify.app/games/raftwars/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5r-oT16xxNncL3IvjdqcmnmsJVguEWj8i2g&s"},
      {name: "GEOMETRY DASH LITE", url: "https://semag.netlify.app/games/gdlite/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6uX6h6pg1m3nNM5avD-E4XMzC91Zrk-QB3Q&s"},
      {name: "SNOW RIDER 3D", url: "snowrider.html", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTy4pT2IOPFKjPSpbVyKRi8dgk6AIVS1-iJWg&s"},
      {name: "SPRINTER", url: "https://main--monumental-truffle-ed74f6.netlify.app/games/sprinter/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREsSD25RWUh8icg82eUFiJr1qyNS51zOkyYA&s"},
      {name: "FNAW", url: "https://hub.flamepass.com/xr/m2kpd27j/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-o73hO6J-mPQqAT-QjR0w3QM0Efnsgqvn4Q&s"},
      {name: "FNAF 1", url: "https://semag.netlify.app/games/fnaf/", image: "https://play-lh.googleusercontent.com/myJ2kwywsCRglKkZuHBq6Aku9PX7HB75v-8KbnTK9JOPU6z0hpD9xtvjiTGqrn-e4eI"},
      {name: "FNAF 2", url: "https://semag.netlify.app/games/fnaf-2/", image: "https://play-lh.googleusercontent.com/GYcyLlHWoZumcal0WmDJJo2rCFyl3Y0mwXm0zaD-C9gC0PJGQMhzOKHfDUVlqSDlag=w240-h480-rw"},
      {name: "FNAF 3", url: "https://semag.netlify.app/games/fnaf-3/", image: "https://play-lh.googleusercontent.com/A9kng-j9BLaA2dhRGsPExmjy9E4vfG-GHefvmyywT0J67ZEPGONIsFYlIokL5EUNfiHF"},
      {name: "FNAF 4", url: "https://semag.netlify.app/games/fnaf-4/", image: "https://play-lh.googleusercontent.com/od7MI1uOFMjj2Kvtk4Tc1Rt-YdDFmgLjE33yZlVINjhbj_NZ5ikZGT_YWpCP0LAGMg=w240-h480-rw"},
      {name: "FNAF 5", url: "https://maddox.page/basic-ruffle-player/html/fnaf5/index.html", image: "https://store-images.s-microsoft.com/image/apps.15528.13548731491092101.6235d68d-70f8-4721-b320-8a2dd5ee8939.2dad79f3-931b-467e-8f28-eb1d4d299f0c?w=400&h=600"},
      {name: "BTD 1", url: "https://semag.netlify.app/games/btd/btd/", image: "https://upload.wikimedia.org/wikipedia/en/e/e6/Bloons_TD_iOS_Logo.jpg"},
      {name: "BTD 2", url: "https://semag.netlify.app/games/btd/btd2/", image: "https://play-lh.googleusercontent.com/t43nQ67qO7N7qlFHccE1YxH8kl5CVA9azzny5ifQlkExk_VhxgMI7lPR1p3OXc-HNWo"},
      {name: "BTD 3", url: "https://semag.netlify.app/games/btd/btd3/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNkQik6Kfg_igNsWtywMROD3rx0OQc46rvAg&s"},
      {name: "BTD 4", url: "https://semag.netlify.app/games/btd/btd4/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO4JjRGDQHtC0iwjCNCqJU9E1R_avpgrzozQ&s"},
      {name: "CLUSTER RUSH", url: "https://semag.netlify.app/games/clusterrush/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvzeAKIb6KcDTMVaUW5LifybFVwmkvU4JE6A&s"},
      {name: "ADVENTURE CAPTIALIST", url: "https://semag.netlify.app/games/adventurecapitalist/", image: "https://upload.wikimedia.org/wikipedia/en/1/13/AdVenture_Capitalist_%282014_video_game%29.png"},
      {name: "AMONGUS FANGAME", url: "https://semag.netlify.app/games/amongus/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjk9vgGhbuEUkUejprdfgjvuBjUTeiuGKoeQ&s"},
      {name: "COOKIE CLICKER", url: "https://semag.netlify.app/games/cookieclicker/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSg8DKYZXE0eD0gQXrJXRUd7OO6MFlQJkenw&s"},
      {name: "HAPPY WHEELS", url: "https://semag.netlify.app/games/happywheels/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPLSuJ9h0TNhBxap5wL0dkMcJpTds2wOuE3Q&s"},
      {name: "LEARN 2 FLY", url: "learntofly/index.html", image: "https://play-lh.googleusercontent.com/WYyWLDBs2bj-KtDBhg7jSqW34nYzyoFTvtKaYBTt2J6SAA05dqEZGI8s1h2LQQV3BHc"},
      {name: "DOODLE JUMP", url: "https://semag.netlify.app/games/doodlejump/", image: "https://play-lh.googleusercontent.com/aHnvdFTx0LVyfVHQLX51VcWBYkSVGvggr4FvIiP-iwBu4pKBiOQA1OnRi_nyFdCWqlU8"},
      {name: "CUT THE ROPE", url: "https://semag.netlify.app/games/cuttherope/", image: "https://play-lh.googleusercontent.com/j8C5NNlvSd8UzBvdije6tKpv2DfXKr6ejIF1jHASKLRBjpB485OL7IbwzqrxSAVktdMj"},
      {name: "TEMPLE RUN 2", url: "https://semag.netlify.app/games/templerun2/", image: "https://i.pinimg.com/736x/07/ef/10/07ef10c982b089babd27eb19228264e5.jpg"},
      {name: "DUCK LIFE", url: "ducklife/index.html", image: "https://play-lh.googleusercontent.com/AUGkRrKMtUCLVE9vCvlfMY9Ny9EBqzx17yejVtEEhvpkw-H6lJlvBHgCMqPJm8HV_tM"},
      {name: "RUN 3", url: "https://student-desmos.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSV5ui-eWyj4PU5ZICXnAjoxmtxl3-iJE8ZrQ&s"},
      {name: "TANUKI SUNSET", url: "https://semag.netlify.app/games/tanukisunset/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOcTC-RzI25sshc_uu9nx19UAsXw6N8IW7qg&s"},
      {name: "DRIFT HUNTERS", url: "https://semag.netlify.app/games/drifthunters/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo0uUffgz5UydHAH9UcHsw3XWJKxx2FnpabA&s"},
      {name: "DRIFT BOSS", url: "https://semag.netlify.app/games/driftboss/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS8ef1NUNCmqUHh1sBx1ErBIh3UO_GhCkUlw&s"},
      {name: "5K RUN", url: "https://5krun.vercel.app/", image: "https://thumbs.dreamstime.com/b/print-173898184.jpg"},
      {name: "SWERVE", url: "https://s3-eu-west-1.amazonaws.com/apps.playcanvas.com/VecAxR3e/index.html", image: "https://s3-eu-west-1.amazonaws.com/apps.playcanvas.com/iJa0TBSq/thumbs/360.jpg"},
      {name: "BATTLESHIPS", url: "https://semag.netlify.app/games/battleships/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHKRODjcZs84JaHY3NuQ7zflEzdfxksdPHDg&s"},
      {name: "SUBWAY SURFERS", url: "https://semag.netlify.app/games/subwaysurfers/", image: "https://play-lh.googleusercontent.com/7XhuH3jCxk8ledQ77YBsqthLVgDgAtiVP86b92_6Ljk6JJ7BUwDxidVscphfuAv05Ss"},
      {name: "LINE RIDER", url: "https://lr.conundrumer.com/", image: "https://m.media-amazon.com/images/I/51+1xhI9PWL.png"},
      {name: "DRIVE MAD", url: "https://drive-mad-ten.vercel.app/", image: "https://play-lh.googleusercontent.com/7l3WAPbei9MXrxnCzImpXi2VxjEBtgDl0htwvTnA-YqpJAuQJPpSiby1oB8LZMgD0IAy"},
      {name: "ROM EMULATOR", url: "https://emulatorjs.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYYe9y5BUdfVjyiFWb5lyc6QAc_0AJIroJ-A&s"},
      {name: "PAPER IO 2", url: "https://semag.netlify.app/games/paperio2/", image: "https://play-lh.googleusercontent.com/SWTpYqsX9RN2YirCDnAjQ8qsbgn4UrHkRRGsjwuASnHMVqssIvWKzq82mP82y_ffBSE"},
      {name: "STACK GAME", url: "https://www.tbsnews.net/game-stack/v0.18/index.html", image: "https://play-lh.googleusercontent.com/WRlGQXa9Pav7YZPW-P5X8PAga0lF2T1BAzmasxB9qV_1_om5DgmMbxOFo2SK8ZN5K5k"},
      {name: "CHROME DINO", url: "https://t-rex.vercel.app/", image: "https://play-lh.googleusercontent.com/iiIJq5JmLFYNI1bVz4IBHyoXs508JcEzHhOgau69bnveF9Wat51-ax9LMPVOlneKwqg"},
      {name: "TETRIS", url: "https://react-tetris-ts.sierrao.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRx64MJCiesJZ0JZRddB2aZEgc7GttsPM6HUw&s"},
      {name: "2048", url: "https://2048-three.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnISndXFU8bvZ8tFr_bAZTViHprn8CpQs4UA&s"},
      {name: "SIMPLE CHESS", url: "https://chessgame.vercel.app/", image: "https://media.istockphoto.com/id/1308228271/vector/chess-pieces-vector-illustration-chess-pieces-king-knight-rook-pawns-on-a-chessboard.jpg?s=612x612&w=0&k=20&c=ug278em0geL18792TbEuxZxg2WSV5KAL5-5Ss-eey4g="},
      {name: "CROSSY ROAD", url: "https://cro.vercel.app/", image: "https://upload.wikimedia.org/wikipedia/en/7/71/Crossy_Road_icon.jpeg"},
      {name: "ROOFTOP SNIPERS", url: "https://rooftop-snipers-1.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvaeAaTYXV7klna_LSqC9ZJW1fbZK0Y0lmYA&s"},
      {name: "WALL RIDER", url: "https://d1sjxq8pnwjv9j.cloudfront.net/", image: "images/wall_rider.png"},
      {name: "RACEKART", url: "https://www.stat2games.sites.grinnell.edu/games/racekart.html", image: "https://cdn.vectorstock.com/i/500p/02/26/go-kart-racing-icon-vector-51550226.jpg"},
      {name: "AWESOME TANKS 2", url: "https://awesome-tanks-2-eight.vercel.app/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFnqffDTr0FviRCWS5jdBAbZIiPAQUlV2rQg&s"},
      {name: "NEON RIDER", url: "https://polytrack.wuaze.com/neonrider/index.html", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2P5zeYAedeLT03BQibum4kMfH1Eryrf5xcA&s"},
      {name: "POKEMON EMERALD", url: "https://semag.netlify.app/games/pokemonemerald/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSN81yRnNb14aik3_gqqCXjLs7Aa-Z6w_2XkA&s"},
      {name: "POKEMON FIRE RED", url: "https://semag.netlify.app/games/pokemonfirered/", image: "https://i.pinimg.com/736x/1c/e9/04/1ce9048dde58f818fcba01f5f7705a4c.jpg"},
      {name: "POKEMON LEAF GREEEN", url: "https://semag.netlify.app/games/pokemonleafgreen/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPFh76ih9sm9pUo_UBT4bW8jzBqfrkD1sqDA&s"},
      {name: "POKEMON RUBY", url: "https://semag.netlify.app/games/pokemonruby/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCRQmoH9gnVeA2l-myQGdmQzBL8Er_vm9XSA&s"},
      {name: "POKEMON SAPPHIRE", url: "https://semag.netlify.app/games/pokemonsapphire/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVrxyceevmHuIdnAvE1JOI-eqM8mc0jNuAGg&s"},
      {name: "POKEMON DIAMOND", url: "https://semag.netlify.app/games/pokemondiamond/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8NBgOMVP5B-BvFAVdiNCxX5s6vMxcLKodCg&s"},
      {name: "POKEMON PLATNIUM", url: "https://semag.netlify.app/games/pokemonplatinum/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_3qlRXnFt6pKszxLO-lWqOdyhFtppAsFXIA&s"},
      {name: "POKEMON SOUL-SILVER", url: "https://semag.netlify.app/games/pokemonsoulsilver/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReKSzVfqbAanO83BWARcGqNtt-2Z_URzaAYA&s"},
      {name: "POKEMON UNBOUND", url: "https://semag.netlify.app/games/pokemonunbound/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv323BAeGold9LscJYCoOrkl4nbMO7v6bUPQ&s"},
      {name: "POKEMON STADIUM", url: "https://semag.netlify.app/games/pokemonstadium/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyPtWehxdnqTt7js_TcQtq3Z3yqGlLZ0BFcA&s"},
      {name: "POKEMON SNAP", url: "https://semag.netlify.app/games/pokemonsnap/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsnBaIjKcvy01olRpoqTiMQrziIwHXPFbYqg&s"},
      {name: "POKEMON YELLOW", url: "https://semag.netlify.app/games/pokemonyellow/", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjykxuumBTh_UOSMMUyqWGYgAu2dLYWCGAfA&s"},
    ];
